[package]
name = "render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
crossterm = "0.27.0"
tokio = "1.37.0"
tui = "0.19.0"

[dev-dependencies]
tokio-test = "0.4.4"
unimock = "0.6.5"
