[package]
name = "soundcloud-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mockito = "1.4.0"
reqwest = "0.12.4"
serde_json = "1.0.116"
tokio = { version = "1.37.0", features = ["full"] }

[dev-dependencies]
tokio-test = "0.4.4"
unimock = "0.6.5"
