[package]
name = "player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.83"
bytes = "1.6.0"
futures = "0.3.30"
m3u8-rs = "6.0.0"
reqwest = "0.12.4"
rodio = "0.17.3"
tokio = {version = "1.37.0", features = ["full"]}

[dev-dependencies]
mockall = "0.12.1"
tokio-test = "0.4.4"
