[package]
name = "soundcloud-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.8.0"
tokio = { version = "1.39.2", features = ["full"] }

[dev-dependencies]
rand = "0.8.5"
