name: Continuous Integration

on: [pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: install default tooling
        run: apt update -y && apt-get install -y curl build-essential pkg-config libssl-dev libasound2-dev
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: install default tooling
        run: apt update -y && apt-get install -y curl build-essential pkg-config libssl-dev libasound2-dev
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: install default tooling
        run: apt update -y && apt-get install -y curl build-essential pkg-config libssl-dev libasound2-dev
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: install default tooling
        run: apt update -y && apt-get install -y curl build-essential pkg-config libssl-dev libasound2-dev
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
